const colors = {
  light: {
    text: "#ffffff",
    tint: "#a855f7",
    background: "#0a0a0a",
    foreground: "#ffffff",
    card: "#141414",
    cardForeground: "#ffffff",
    primary: "#a855f7",
    primaryForeground: "#ffffff",
    secondary: "#1a1a1a",
    secondaryForeground: "#e0e0e0",
    muted: "#1a1a1a",
    mutedForeground: "#888888",
    accent: "#06b6d4",
    accentForeground: "#ffffff",
    destructive: "#f43f5e",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#1e1e1e",
    purple: "#a855f7",
    cyan: "#06b6d4",
    pink: "#f43f5e",
    lime: "#84cc16",
  },
  dark: {
    text: "#ffffff",
    tint: "#a855f7",
    background: "#0a0a0a",
    foreground: "#ffffff",
    card: "#141414",
    cardForeground: "#ffffff",
    primary: "#a855f7",
    primaryForeground: "#ffffff",
    secondary: "#1a1a1a",
    secondaryForeground: "#e0e0e0",
    muted: "#1a1a1a",
    mutedForeground: "#888888",
    accent: "#06b6d4",
    accentForeground: "#ffffff",
    destructive: "#f43f5e",
    destructiveForeground: "#ffffff",
    border: "#2a2a2a",
    input: "#1e1e1e",
    purple: "#a855f7",
    cyan: "#06b6d4",
    pink: "#f43f5e",
    lime: "#84cc16",
  },
  radius: 12,
};

export default colors;
