import type { Exercise } from "./types";

export const exerciseLibrary: Exercise[] = [
  // ============ CHEST ============
  {
    id: "1", name: "Bench Press", focus: "reps_weight", equipment: "Barbell", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Pectoralis Major"], secondaryMuscles: ["Triceps", "Front Deltoids"],
    description: "The king of upper body strength exercises, building mass and pressing power across the entire chest.",
    instructions: [
      "Lie flat on a bench with feet planted firmly on the floor.",
      "Grip the bar slightly wider than shoulder width with wrists stacked over elbows.",
      "Unrack the bar and hold it directly over your shoulders with locked elbows.",
      "Lower the bar in a controlled arc to mid-chest, tucking elbows to about 45 degrees.",
      "Drive the bar up explosively, locking out at the top without losing chest contraction.",
    ],
    tips: ["Keep shoulder blades retracted and pinned to the bench.", "Maintain a slight arch in your lower back.", "Don't bounce the bar off your chest."],
  },
  {
    id: "2", name: "Incline Bench Press", focus: "reps_weight", equipment: "Barbell", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Upper Pectoralis"], secondaryMuscles: ["Front Deltoids", "Triceps"],
    description: "Targets the upper chest fibers for a fuller, more aesthetic chest development.",
    instructions: [
      "Set bench to a 30-45 degree incline.",
      "Lie back and grip the bar slightly wider than shoulder width.",
      "Unrack and hold above your upper chest with locked elbows.",
      "Lower the bar in a controlled motion to your upper chest.",
      "Press up powerfully, keeping elbows tracking under the bar.",
    ],
    tips: ["Steeper angles shift work to shoulders — keep below 45°.", "Drive feet into the floor for stability."],
  },
  {
    id: "3", name: "Decline Bench Press", focus: "reps_weight", equipment: "Barbell", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Lower Pectoralis"], secondaryMuscles: ["Triceps"],
    description: "Emphasizes the lower portion of the chest while reducing shoulder strain.",
    instructions: [
      "Set bench to a 15-30 degree decline and secure feet.",
      "Grip the bar slightly wider than shoulder width.",
      "Unrack the bar and hold over your lower chest.",
      "Lower under control to the lower chest.",
      "Press the bar up to full extension.",
    ],
    tips: ["Have a spotter for safety on declines.", "Use a slightly narrower grip than flat bench."],
  },
  {
    id: "4", name: "Dumbbell Bench Press", focus: "reps_weight", equipment: "Dumbbell", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Pectoralis Major"], secondaryMuscles: ["Triceps", "Front Deltoids"],
    description: "Allows greater range of motion and addresses muscle imbalances between sides.",
    instructions: [
      "Sit on a flat bench with dumbbells resting on your thighs.",
      "Lie back, kicking the dumbbells up to shoulder level.",
      "Press both dumbbells up over your chest with palms facing forward.",
      "Lower under control until elbows are slightly below chest level.",
      "Press back up, squeezing chest at the top.",
    ],
    tips: ["Keep wrists straight and stacked over elbows.", "Don't crash the dumbbells together at the top."],
  },
  {
    id: "5", name: "Incline Dumbbell Press", focus: "reps_weight", equipment: "Dumbbell", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Upper Pectoralis"], secondaryMuscles: ["Front Deltoids", "Triceps"],
    description: "Combines incline angle with dumbbell range of motion for upper chest growth.",
    instructions: [
      "Set bench to 30-45 degree incline.",
      "Sit with dumbbells on thighs, then lie back kicking them to shoulder level.",
      "Press both dumbbells up above your upper chest.",
      "Lower in a controlled arc to chest level.",
      "Press up and squeeze chest at the top.",
    ],
    tips: ["Keep elbows at 45° to protect shoulders.", "Don't let elbows flare wide."],
  },
  {
    id: "6", name: "Dumbbell Fly", focus: "reps_weight", equipment: "Dumbbell", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Pectoralis Major"], secondaryMuscles: ["Front Deltoids"],
    description: "Isolates the chest with a stretching arc motion for definition and width.",
    instructions: [
      "Lie flat on a bench holding dumbbells over your chest with palms facing each other.",
      "Keep a slight bend in your elbows throughout.",
      "Lower the dumbbells out to your sides in a wide arc.",
      "Stop when you feel a deep stretch in your chest.",
      "Squeeze the chest to bring the dumbbells back together over your chest.",
    ],
    tips: ["Use lighter weight than you think — form is everything.", "Don't bend the elbows further during the lift."],
  },
  {
    id: "7", name: "Cable Crossover", focus: "reps_weight", equipment: "Cable", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Pectoralis Major"], secondaryMuscles: ["Front Deltoids"],
    description: "Constant tension chest isolation that creates the inner-chest squeeze.",
    instructions: [
      "Set cables at the top of the pulley stack and grab a handle in each hand.",
      "Step forward into a split stance with a slight forward lean.",
      "Start with arms wide and elbows slightly bent.",
      "Pull the handles down and across in front of your body.",
      "Squeeze chest at the bottom, then return slowly.",
    ],
    tips: ["Maintain elbow angle throughout — this is a fly, not a press.", "Vary cable height to hit upper, mid, lower chest."],
  },
  {
    id: "8", name: "Pec Deck", focus: "reps_weight", equipment: "Machine", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Pectoralis Major"], secondaryMuscles: ["Front Deltoids"],
    description: "Beginner-friendly fly variation that locks you into the right path.",
    instructions: [
      "Sit on the pec deck with back flat against the pad.",
      "Grip the handles with elbows bent at 90 degrees on the pads.",
      "Squeeze your chest to bring the pads together in front of you.",
      "Hold the squeeze for a beat.",
      "Slowly return to the starting position with control.",
    ],
    tips: ["Don't let weight stack touch between reps — keep tension.", "Adjust seat so handles are at chest level."],
  },
  {
    id: "9", name: "Push-up", focus: "reps_weight", equipment: "Bodyweight", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Pectoralis Major"], secondaryMuscles: ["Triceps", "Front Deltoids", "Core"],
    description: "Foundational pressing movement that builds chest, shoulders, triceps, and core.",
    instructions: [
      "Start in a high plank with hands slightly wider than shoulders.",
      "Brace your core and keep your body in a straight line head to heels.",
      "Lower your chest to the floor by bending your elbows to about 45°.",
      "Push the floor away to return to the start position.",
      "Lock out elbows at the top without sagging the hips.",
    ],
    tips: ["Don't let hips sag or pike up.", "Add weight on your back to scale up."],
  },
  {
    id: "10", name: "Chest Dip", focus: "reps_weight", equipment: "Bodyweight", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Lower Pectoralis"], secondaryMuscles: ["Triceps", "Front Deltoids"],
    description: "Bodyweight dip variation with forward lean to hammer the chest.",
    instructions: [
      "Grip parallel bars and press up to a supported start.",
      "Lean your torso forward at about 30 degrees.",
      "Lower yourself by bending your elbows out slightly.",
      "Descend until your shoulders are just below your elbows.",
      "Press back up while maintaining the forward lean.",
    ],
    tips: ["Don't go too low if you have shoulder issues.", "Add a dip belt for weighted progression."],
  },
  {
    id: "11", name: "Machine Chest Press", focus: "reps_weight", equipment: "Machine", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Pectoralis Major"], secondaryMuscles: ["Triceps", "Front Deltoids"],
    description: "Stable, fixed-path press that's great for high-volume work or beginners.",
    instructions: [
      "Adjust seat so handles align with your mid-chest.",
      "Sit with back flat against the pad and feet planted.",
      "Grip the handles and press them forward to full extension.",
      "Squeeze chest at lockout.",
      "Lower with control until elbows reach about 90°.",
    ],
    tips: ["Keep shoulder blades pinched.", "Don't let weight stack rest between reps."],
  },
  {
    id: "12", name: "Incline Push-up", focus: "reps_weight", equipment: "Bodyweight", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Lower Pectoralis"], secondaryMuscles: ["Triceps"],
    description: "Easier push-up variation with hands elevated, perfect for high reps.",
    instructions: [
      "Place hands on a bench or sturdy elevated surface.",
      "Step feet back into a straight-body plank.",
      "Lower chest to the bench by bending elbows.",
      "Press back up to full extension.",
    ],
    tips: ["Higher surface = easier.", "Great for beginners building to floor push-ups."],
  },

  // ============ BACK ============
  {
    id: "13", name: "Deadlift", focus: "reps_weight", equipment: "Barbell", category: "Back",
    movementPattern: "hinge",
    primaryMuscles: ["Erector Spinae", "Glutes", "Hamstrings"], secondaryMuscles: ["Lats", "Traps", "Core"],
    description: "The ultimate strength builder — works nearly every muscle in your posterior chain.",
    instructions: [
      "Stand with feet hip-width apart, bar over the middle of your feet.",
      "Hinge down and grip the bar just outside your knees.",
      "Drop your hips, lift your chest, and engage your lats.",
      "Drive through your heels and stand up, keeping the bar close to your body.",
      "Lock out hips and shoulders at the top, then reverse the motion.",
    ],
    tips: ["Keep the bar in contact with your shins.", "Don't round your lower back.", "Reset your setup every rep."],
  },
  {
    id: "14", name: "Romanian Deadlift", focus: "reps_weight", equipment: "Barbell", category: "Back",
    movementPattern: "hinge",
    primaryMuscles: ["Hamstrings", "Glutes"], secondaryMuscles: ["Erector Spinae", "Lats"],
    description: "Hip-hinge focused deadlift variation that emphasizes hamstrings and glutes.",
    instructions: [
      "Stand holding a bar at hip level with overhand grip.",
      "Soften knees slightly — they stay in this position throughout.",
      "Hinge at the hips, pushing them back as the bar slides down your thighs.",
      "Lower until you feel a deep hamstring stretch (usually mid-shin).",
      "Drive hips forward to return to standing.",
    ],
    tips: ["Keep the bar close to your legs the whole time.", "Maintain a neutral spine — don't round."],
  },
  {
    id: "15", name: "Pull-up", focus: "reps_weight", equipment: "Bodyweight", category: "Back",
    movementPattern: "vertical_pull",
    primaryMuscles: ["Lats"], secondaryMuscles: ["Biceps", "Rear Deltoids", "Rhomboids"],
    description: "The gold standard of upper body pulling strength.",
    instructions: [
      "Hang from a pull-up bar with hands slightly wider than shoulders, palms facing away.",
      "Engage your lats by pulling your shoulder blades down.",
      "Pull your chest toward the bar by driving your elbows down and back.",
      "Touch the bar with your upper chest at the top.",
      "Lower yourself with control to a full hang.",
    ],
    tips: ["Don't kip or swing — full strict range.", "Use a band or assisted machine if needed."],
  },
  {
    id: "16", name: "Chin-up", focus: "reps_weight", equipment: "Bodyweight", category: "Back",
    movementPattern: "vertical_pull",
    primaryMuscles: ["Lats", "Biceps"], secondaryMuscles: ["Rhomboids", "Rear Deltoids"],
    description: "Underhand-grip pull-up that hits the biceps harder than a standard pull-up.",
    instructions: [
      "Hang from a bar with palms facing you, hands shoulder-width.",
      "Pull yourself up by driving your elbows down to your sides.",
      "Bring your chin over the bar.",
      "Lower with control to a full hang.",
    ],
    tips: ["Easier than pull-ups for most people.", "Squeeze biceps at the top."],
  },
  {
    id: "17", name: "Lat Pulldown", focus: "reps_weight", equipment: "Cable", category: "Back",
    movementPattern: "vertical_pull",
    primaryMuscles: ["Lats"], secondaryMuscles: ["Biceps", "Rear Deltoids"],
    description: "Vertical pull machine variant ideal for building lat width.",
    instructions: [
      "Sit at the lat pulldown machine with thighs secured under the pad.",
      "Grip the bar slightly wider than shoulder width with palms facing forward.",
      "Lean back slightly and pull the bar down to your upper chest.",
      "Squeeze your shoulder blades together at the bottom.",
      "Slowly let the bar return to the top with control.",
    ],
    tips: ["Don't pull behind the neck — risky for shoulders.", "Keep chest up throughout."],
  },
  {
    id: "18", name: "Barbell Row", focus: "reps_weight", equipment: "Barbell", category: "Back",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Rear Deltoids", "Biceps", "Erector Spinae"],
    description: "Horizontal rowing movement that builds back thickness and pulling strength.",
    instructions: [
      "Stand with feet hip-width, bar at shins, overhand grip just outside knees.",
      "Hinge at the hips until torso is about 45° to the floor.",
      "Pull the bar to your lower chest/upper abs by driving elbows back.",
      "Squeeze shoulder blades together at the top.",
      "Lower the bar with control to the start.",
    ],
    tips: ["Don't use leg drive or momentum.", "Keep core tight to protect lower back."],
  },
  {
    id: "19", name: "T-Bar Row", focus: "reps_weight", equipment: "Barbell", category: "Back",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Rear Deltoids", "Biceps"],
    description: "Allows heavier loading than dumbbell rows with great mid-back focus.",
    instructions: [
      "Stand straddling a loaded T-bar or landmine setup.",
      "Hinge forward and grip the V-handle with both hands.",
      "Row the bar up to your chest by driving elbows back.",
      "Squeeze your back at the top.",
      "Lower with control to full stretch.",
    ],
    tips: ["Wedge bar in a corner if no T-bar station.", "Keep chest tall."],
  },
  {
    id: "20", name: "Dumbbell Row", focus: "reps_weight", equipment: "Dumbbell", category: "Back",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Biceps", "Rear Deltoids"],
    description: "Single-arm row that addresses imbalances and isolates each side.",
    instructions: [
      "Place one knee and same-side hand on a bench for support.",
      "Hold a dumbbell in the opposite hand, arm hanging straight down.",
      "Row the dumbbell to your lower ribs by driving the elbow up and back.",
      "Squeeze your back at the top.",
      "Lower with control to the bottom.",
    ],
    tips: ["Don't twist your torso to lift more weight.", "Keep your back flat and parallel to the floor."],
  },
  {
    id: "21", name: "Seated Cable Row", focus: "reps_weight", equipment: "Cable", category: "Back",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Biceps", "Rear Deltoids"],
    description: "Constant-tension row that emphasizes mid-back development.",
    instructions: [
      "Sit at the cable row station with feet on the platform, knees slightly bent.",
      "Grip the handle and sit tall with arms extended.",
      "Pull the handle to your abdomen by driving elbows back.",
      "Squeeze shoulder blades together at the end.",
      "Slowly extend arms back to the start.",
    ],
    tips: ["Don't rock your torso back and forth.", "Keep chest tall, shoulders down."],
  },
  {
    id: "22", name: "Face Pull", focus: "reps_weight", equipment: "Cable", category: "Back",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["Rear Deltoids", "Rhomboids"], secondaryMuscles: ["Traps"],
    description: "Critical for shoulder health and posture — hits often-neglected rear delts.",
    instructions: [
      "Set cable at upper chest height with a rope attachment.",
      "Step back and grip the rope with palms facing each other.",
      "Pull the rope toward your face, separating your hands as you pull.",
      "Externally rotate so your hands end beside your ears, elbows high.",
      "Slowly return to start with control.",
    ],
    tips: ["Use lighter weight than you think.", "Imagine making a double biceps pose."],
  },
  {
    id: "23", name: "Single-Arm Lat Pulldown", focus: "reps_weight", equipment: "Cable", category: "Back",
    movementPattern: "vertical_pull",
    primaryMuscles: ["Lats"], secondaryMuscles: ["Biceps", "Rear Deltoids"],
    description: "Unilateral pulldown that gives a deeper stretch and full range of motion.",
    instructions: [
      "Attach a single handle to the high pulley.",
      "Kneel or sit and grab with one hand, arm fully extended overhead.",
      "Pull the handle down to your shoulder by driving the elbow down.",
      "Squeeze your lat at the bottom.",
      "Slowly return to a full overhead stretch.",
    ],
    tips: ["Keep your torso stable — don't twist.", "Get a deep stretch at the top."],
  },
  {
    id: "24", name: "Pendlay Row", focus: "reps_weight", equipment: "Barbell", category: "Back",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Rear Deltoids", "Biceps"],
    description: "Explosive row from a dead stop on the floor — builds raw pulling power.",
    instructions: [
      "Set up like a deadlift but with torso parallel to the floor.",
      "Grip the bar shoulder-width, overhand.",
      "Explosively row the bar to your lower chest.",
      "Lower the bar all the way back to the floor.",
      "Reset and repeat each rep from a dead stop.",
    ],
    tips: ["Keep torso parallel — don't pop up.", "Pause briefly on the floor between reps."],
  },
  {
    id: "25", name: "Hyperextension", focus: "reps_weight", equipment: "Machine", category: "Back",
    movementPattern: "hinge",
    primaryMuscles: ["Erector Spinae"], secondaryMuscles: ["Glutes", "Hamstrings"],
    description: "Strengthens the lower back and posterior chain safely.",
    instructions: [
      "Position yourself face down on the hyperextension bench, hips on the pad.",
      "Cross arms on chest or hold a plate for added load.",
      "Lower your torso by hinging at the hips.",
      "Stop when you feel a stretch in your hamstrings.",
      "Raise back up to a straight body line — don't hyperextend.",
    ],
    tips: ["Don't arch the back at the top.", "Move slow and controlled."],
  },

  // ============ LEGS ============
  {
    id: "26", name: "Back Squat", focus: "reps_weight", equipment: "Barbell", category: "Legs",
    movementPattern: "squat",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Hamstrings", "Core", "Erector Spinae"],
    description: "The king of lower body exercises — builds total leg strength and size.",
    instructions: [
      "Set the bar at upper-chest height in the rack and step under it.",
      "Position the bar on your upper traps, grip slightly wider than shoulders.",
      "Step back and set feet shoulder-width with toes slightly out.",
      "Brace core, sit back and down until thighs are at least parallel to floor.",
      "Drive through your heels to stand back up explosively.",
    ],
    tips: ["Knees track over toes.", "Keep chest up throughout.", "Take a big breath in at the top, exhale at the lockout."],
  },
  {
    id: "27", name: "Front Squat", focus: "reps_weight", equipment: "Barbell", category: "Legs",
    movementPattern: "squat",
    primaryMuscles: ["Quadriceps"], secondaryMuscles: ["Glutes", "Core", "Upper Back"],
    description: "Bar in front position emphasizes quads and demands an upright torso.",
    instructions: [
      "Set bar in rack at chest height.",
      "Position bar across front delts with elbows up high (clean grip or cross-arm).",
      "Step back and set feet shoulder-width.",
      "Squat down keeping torso vertical and elbows up.",
      "Drive up through heels back to standing.",
    ],
    tips: ["Keep elbows pointed forward.", "Don't let the elbows drop or you'll dump the bar."],
  },
  {
    id: "28", name: "Leg Press", focus: "reps_weight", equipment: "Machine", category: "Legs",
    movementPattern: "squat",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Hamstrings"],
    description: "Heavy leg work without taxing your spine or balance.",
    instructions: [
      "Sit in the leg press with back flat against the pad.",
      "Place feet shoulder-width on the platform, mid-foot position.",
      "Release the safeties and lower the platform by bending knees.",
      "Stop when knees reach 90° (or just before lower back rounds).",
      "Press the platform back up without locking out the knees.",
    ],
    tips: ["Don't let knees cave inward.", "Keep lower back pressed into the pad."],
  },
  {
    id: "29", name: "Hack Squat", focus: "reps_weight", equipment: "Machine", category: "Legs",
    movementPattern: "squat",
    primaryMuscles: ["Quadriceps"], secondaryMuscles: ["Glutes", "Hamstrings"],
    description: "Machine squat variation that locks you into a quad-dominant pattern.",
    instructions: [
      "Position back and shoulders against the pads in the hack squat.",
      "Place feet shoulder-width on the platform.",
      "Release the safety handles.",
      "Lower under control until thighs are parallel.",
      "Drive up through your heels back to the start.",
    ],
    tips: ["Lower foot placement = more quads.", "Keep chest up against the pad."],
  },
  {
    id: "30", name: "Bulgarian Split Squat", focus: "reps_weight", equipment: "Dumbbell", category: "Legs",
    movementPattern: "lunge",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Hamstrings", "Core"],
    description: "Brutal single-leg exercise that exposes weaknesses and builds unilateral strength.",
    instructions: [
      "Stand a few feet in front of a bench, holding dumbbells at your sides.",
      "Place the top of one foot on the bench behind you.",
      "Lower your back knee toward the floor by bending your front leg.",
      "Stop just before your back knee touches the ground.",
      "Drive through the front heel to return to standing.",
    ],
    tips: ["Keep most of your weight on the front leg.", "Front foot far enough out that knee stays over ankle."],
  },
  {
    id: "31", name: "Walking Lunge", focus: "reps_weight", equipment: "Dumbbell", category: "Legs",
    movementPattern: "lunge",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Hamstrings", "Core"],
    description: "Dynamic lunges that build legs and challenge balance and coordination.",
    instructions: [
      "Stand with dumbbells at your sides.",
      "Step forward into a lunge, lowering your back knee toward the floor.",
      "Drive through the front heel to step the back foot forward into the next lunge.",
      "Continue alternating legs walking forward.",
    ],
    tips: ["Keep torso upright.", "Long stride hits glutes more, short stride hits quads more."],
  },
  {
    id: "32", name: "Leg Extension", focus: "reps_weight", equipment: "Machine", category: "Legs",
    movementPattern: "isolation_extension",
    primaryMuscles: ["Quadriceps"], secondaryMuscles: [],
    description: "Pure quad isolation that finishes off leg day with high volume.",
    instructions: [
      "Sit on the leg extension machine with knees aligned with the pivot.",
      "Place shins behind the pad, just above the ankles.",
      "Extend your legs by contracting your quads.",
      "Hold the squeeze at the top for a second.",
      "Lower under control to a 90° knee bend.",
    ],
    tips: ["Don't slam the weight stack.", "Pause at the top for max quad activation."],
  },
  {
    id: "33", name: "Lying Leg Curl", focus: "reps_weight", equipment: "Machine", category: "Legs",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Hamstrings"], secondaryMuscles: ["Calves"],
    description: "Hamstring isolation that builds the back of your legs.",
    instructions: [
      "Lie face down on the leg curl machine with the pad just above your ankles.",
      "Grip the handles for stability.",
      "Curl your heels toward your glutes by contracting your hamstrings.",
      "Squeeze at the top.",
      "Lower under control to start.",
    ],
    tips: ["Don't lift hips off the pad.", "Slow the negative for more growth."],
  },
  {
    id: "34", name: "Seated Leg Curl", focus: "reps_weight", equipment: "Machine", category: "Legs",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Hamstrings"], secondaryMuscles: [],
    description: "Hamstring isolation in a seated position that puts hams in a stretched position.",
    instructions: [
      "Sit on the machine with back flat and pad just above ankles.",
      "Secure the lap pad over your thighs.",
      "Curl your legs down by squeezing hamstrings.",
      "Hold briefly at peak contraction.",
      "Slowly extend legs back to start.",
    ],
    tips: ["Stretched position makes this superior for hamstring growth.", "Don't lock out the knees at the top."],
  },
  {
    id: "35", name: "Standing Calf Raise", focus: "reps_weight", equipment: "Machine", category: "Legs",
    movementPattern: "isolation_raise",
    primaryMuscles: ["Gastrocnemius"], secondaryMuscles: ["Soleus"],
    description: "Builds the diamond shape of the upper calves.",
    instructions: [
      "Stand on the calf raise platform with balls of feet on the edge.",
      "Lower heels below platform level for a full stretch.",
      "Press up onto your toes as high as possible.",
      "Squeeze the calves at the top.",
      "Lower slowly back to a deep stretch.",
    ],
    tips: ["Full range of motion is critical.", "Pause at the top for one second each rep."],
  },
  {
    id: "36", name: "Seated Calf Raise", focus: "reps_weight", equipment: "Machine", category: "Legs",
    movementPattern: "isolation_raise",
    primaryMuscles: ["Soleus"], secondaryMuscles: ["Gastrocnemius"],
    description: "Targets the soleus — the often-forgotten lower calf muscle.",
    instructions: [
      "Sit with knees under the pad and balls of feet on platform.",
      "Lower heels for a deep calf stretch.",
      "Press up onto your toes.",
      "Squeeze hard at the top.",
      "Lower slowly back to stretch.",
    ],
    tips: ["Bent knees target the soleus specifically.", "Higher reps work well here."],
  },
  {
    id: "37", name: "Hip Thrust", focus: "reps_weight", equipment: "Barbell", category: "Legs",
    movementPattern: "hinge",
    primaryMuscles: ["Glutes"], secondaryMuscles: ["Hamstrings", "Core"],
    description: "The most direct glute-builder you can do.",
    instructions: [
      "Sit on the floor with upper back against a bench, bar over your hips (use a pad).",
      "Plant feet shoulder-width, knees bent.",
      "Drive through heels and squeeze glutes to lift hips up.",
      "At the top, body should form a straight line from knees to shoulders.",
      "Lower hips with control to the floor.",
    ],
    tips: ["Keep chin tucked and ribs down.", "Squeeze glutes hard at the top."],
  },
  {
    id: "38", name: "Sumo Deadlift", focus: "reps_weight", equipment: "Barbell", category: "Legs",
    movementPattern: "hinge",
    primaryMuscles: ["Quadriceps", "Glutes", "Adductors"], secondaryMuscles: ["Hamstrings", "Erector Spinae"],
    description: "Wider stance deadlift that emphasizes legs and reduces lower back stress.",
    instructions: [
      "Stand with feet much wider than shoulders, toes pointed out 30-45°.",
      "Grip the bar with hands inside your knees.",
      "Drop hips, lift chest, push knees out.",
      "Drive through your heels and stand up.",
      "Lock out and reverse the motion.",
    ],
    tips: ["Push knees out over toes.", "Keep torso more upright than conventional deadlift."],
  },
  {
    id: "39", name: "Goblet Squat", focus: "reps_weight", equipment: "Dumbbell", category: "Legs",
    movementPattern: "squat",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Core", "Upper Back"],
    description: "Front-loaded squat that teaches proper form and builds quads.",
    instructions: [
      "Hold a dumbbell vertically against your chest with both hands cupping the top.",
      "Stand with feet shoulder-width.",
      "Squat down keeping chest up and elbows pointed down.",
      "Go as low as your mobility allows.",
      "Drive through heels to stand back up.",
    ],
    tips: ["Great learning tool for new squatters.", "Keep elbows inside the knees at the bottom."],
  },
  {
    id: "40", name: "Step-up", focus: "reps_weight", equipment: "Dumbbell", category: "Legs",
    movementPattern: "lunge",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Hamstrings"],
    description: "Functional unilateral leg exercise for size and balance.",
    instructions: [
      "Hold dumbbells at your sides and stand in front of a sturdy box or bench.",
      "Step up by placing one foot on the box.",
      "Drive through that heel to stand fully on top.",
      "Step back down with the same leg leading.",
      "Repeat or alternate legs.",
    ],
    tips: ["Don't push off the bottom foot — full driving leg.", "Box should be knee height or slightly higher."],
  },
  {
    id: "41", name: "Glute Kickback", focus: "reps_weight", equipment: "Cable", category: "Legs",
    movementPattern: "isolation_extension",
    primaryMuscles: ["Glutes"], secondaryMuscles: ["Hamstrings"],
    description: "Targeted glute isolation that hits the upper glutes hard.",
    instructions: [
      "Attach an ankle cuff to a low cable.",
      "Face the machine and grab it for support.",
      "Kick the working leg straight back, squeezing the glute.",
      "Hold the contraction at the top.",
      "Lower with control to start.",
    ],
    tips: ["Don't arch the lower back.", "Keep movement at the hip, not the lower spine."],
  },

  // ============ SHOULDERS ============
  {
    id: "42", name: "Overhead Press", focus: "reps_weight", equipment: "Barbell", category: "Shoulders",
    movementPattern: "vertical_push",
    primaryMuscles: ["Front Deltoids", "Side Deltoids"], secondaryMuscles: ["Triceps", "Upper Pectoralis", "Core"],
    description: "Standing barbell press — the benchmark of upper body pressing strength.",
    instructions: [
      "Set bar at upper chest height, grip just outside shoulders.",
      "Unrack and stand with bar on front delts, elbows under bar.",
      "Brace core and squeeze glutes.",
      "Press the bar straight up, moving head back slightly to clear it.",
      "Lock out overhead with bar over mid-foot, then lower to start.",
    ],
    tips: ["Don't lean back — keep ribs down.", "Squeeze glutes to protect the lower back."],
  },
  {
    id: "43", name: "Dumbbell Shoulder Press", focus: "reps_weight", equipment: "Dumbbell", category: "Shoulders",
    movementPattern: "vertical_push",
    primaryMuscles: ["Front Deltoids", "Side Deltoids"], secondaryMuscles: ["Triceps", "Upper Pectoralis"],
    description: "Greater range of motion than barbell press and addresses imbalances.",
    instructions: [
      "Sit on a bench with back support, dumbbells at shoulder level, palms forward.",
      "Brace core and press both dumbbells straight up.",
      "Stop just before lockout to keep shoulder tension.",
      "Lower under control until upper arms are parallel to the floor.",
    ],
    tips: ["Keep wrists stacked over elbows.", "Don't slam the dumbbells together at the top."],
  },
  {
    id: "44", name: "Arnold Press", focus: "reps_weight", equipment: "Dumbbell", category: "Shoulders",
    movementPattern: "vertical_push",
    primaryMuscles: ["Front Deltoids", "Side Deltoids"], secondaryMuscles: ["Triceps"],
    description: "Rotating press that hits all three heads of the deltoid.",
    instructions: [
      "Sit with dumbbells at shoulder height, palms facing you (curl-grip).",
      "Press up while rotating wrists outward.",
      "Finish with palms facing forward at the top.",
      "Reverse the motion on the way down.",
    ],
    tips: ["Smooth controlled rotation throughout.", "Use lighter weight than a regular shoulder press."],
  },
  {
    id: "45", name: "Lateral Raise", focus: "reps_weight", equipment: "Dumbbell", category: "Shoulders",
    movementPattern: "isolation_raise",
    primaryMuscles: ["Side Deltoids"], secondaryMuscles: [],
    description: "Builds the cap of the shoulder for that 3D look.",
    instructions: [
      "Stand with dumbbells at your sides, slight bend in elbows.",
      "Lift the dumbbells out to the sides until parallel with the floor.",
      "Lead with your elbows, not your hands.",
      "Pause briefly at the top.",
      "Lower slowly back to start.",
    ],
    tips: ["Use light weight and strict form.", "Don't shrug — keep traps relaxed."],
  },
  {
    id: "46", name: "Cable Lateral Raise", focus: "reps_weight", equipment: "Cable", category: "Shoulders",
    movementPattern: "isolation_raise",
    primaryMuscles: ["Side Deltoids"], secondaryMuscles: [],
    description: "Constant tension lateral raise variation for max side delt growth.",
    instructions: [
      "Set cable to lowest setting, attach a single handle.",
      "Stand sideways to the machine, grab handle with the far hand crossing your body.",
      "Raise the handle out to the side until parallel with the floor.",
      "Pause and squeeze.",
      "Lower with control across your body.",
    ],
    tips: ["Cable provides tension throughout, unlike dumbbells.", "Keep wrist neutral."],
  },
  {
    id: "47", name: "Front Raise", focus: "reps_weight", equipment: "Dumbbell", category: "Shoulders",
    movementPattern: "isolation_raise",
    primaryMuscles: ["Front Deltoids"], secondaryMuscles: ["Upper Pectoralis"],
    description: "Isolates the front of the shoulder for delt definition.",
    instructions: [
      "Stand with dumbbells in front of your thighs, palms facing you.",
      "Raise one or both dumbbells straight up in front of you.",
      "Stop when arms are parallel to the floor.",
      "Lower with control to start.",
    ],
    tips: ["Don't swing.", "Most front delt work comes from pressing — don't overdo this."],
  },
  {
    id: "48", name: "Reverse Fly", focus: "reps_weight", equipment: "Dumbbell", category: "Shoulders",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["Rear Deltoids"], secondaryMuscles: ["Rhomboids", "Traps"],
    description: "Hits the rear delts and improves shoulder posture.",
    instructions: [
      "Hinge forward at the hips with dumbbells hanging below your chest.",
      "With slight elbow bend, raise dumbbells out to the sides.",
      "Squeeze rear delts and shoulder blades together.",
      "Stop when arms are parallel to the floor.",
      "Lower with control.",
    ],
    tips: ["Lighter weight, focus on the squeeze.", "Don't shrug or use traps."],
  },
  {
    id: "49", name: "Reverse Pec Deck", focus: "reps_weight", equipment: "Machine", category: "Shoulders",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["Rear Deltoids"], secondaryMuscles: ["Rhomboids"],
    description: "Locked-in rear delt isolation with constant tension.",
    instructions: [
      "Sit facing into the pec deck machine, chest against the pad.",
      "Grip the handles with arms straight or slightly bent.",
      "Pull the handles back and out to the sides.",
      "Squeeze rear delts and pause.",
      "Return to start under control.",
    ],
    tips: ["Don't pull with your arms — drive with rear delts.", "Keep chest pressed to the pad."],
  },
  {
    id: "50", name: "Upright Row", focus: "reps_weight", equipment: "Barbell", category: "Shoulders",
    movementPattern: "vertical_pull",
    primaryMuscles: ["Side Deltoids", "Traps"], secondaryMuscles: ["Biceps"],
    description: "Controversial but effective shoulder builder when done right.",
    instructions: [
      "Hold a barbell with hands shoulder-width, arms hanging in front.",
      "Pull the bar straight up your body, leading with your elbows.",
      "Stop when bar reaches mid-chest height (don't go higher).",
      "Lower with control.",
    ],
    tips: ["Wider grip is safer for shoulders.", "If you feel pinching, switch to lateral raises."],
  },
  {
    id: "51", name: "Shrug", focus: "reps_weight", equipment: "Dumbbell", category: "Shoulders",
    movementPattern: "isolation_raise",
    primaryMuscles: ["Traps"], secondaryMuscles: [],
    description: "Direct trap-builder for that powerful neck-to-shoulder line.",
    instructions: [
      "Stand holding heavy dumbbells at your sides.",
      "Shrug shoulders straight up toward your ears.",
      "Hold at the top for a beat.",
      "Lower with control.",
    ],
    tips: ["Don't roll the shoulders.", "Use straps if grip is the limiting factor."],
  },
  {
    id: "52", name: "Machine Shoulder Press", focus: "reps_weight", equipment: "Machine", category: "Shoulders",
    movementPattern: "vertical_push",
    primaryMuscles: ["Front Deltoids", "Side Deltoids"], secondaryMuscles: ["Triceps"],
    description: "Stable pressing variation for high volume or beginners.",
    instructions: [
      "Sit with back flat against the pad, handles at shoulder height.",
      "Grip the handles and press straight up to near lockout.",
      "Lower with control to shoulder height.",
    ],
    tips: ["Adjust seat so handles align with shoulders.", "Keep core braced."],
  },

  // ============ ARMS ============
  {
    id: "53", name: "Barbell Curl", focus: "reps_weight", equipment: "Barbell", category: "Arms",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Biceps"], secondaryMuscles: ["Forearms"],
    description: "Classic mass-builder for the biceps.",
    instructions: [
      "Stand with feet hip-width, barbell held at thighs with shoulder-width underhand grip.",
      "Keep elbows pinned to your sides.",
      "Curl the bar up toward your shoulders by flexing the biceps.",
      "Squeeze hard at the top.",
      "Lower with control to full extension.",
    ],
    tips: ["Don't swing or use momentum.", "Don't let elbows drift forward."],
  },
  {
    id: "54", name: "Dumbbell Curl", focus: "reps_weight", equipment: "Dumbbell", category: "Arms",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Biceps"], secondaryMuscles: ["Forearms"],
    description: "Allows wrist rotation for full bicep contraction.",
    instructions: [
      "Stand with dumbbells at your sides, palms facing in.",
      "Curl one dumbbell up while rotating the wrist so palm faces up.",
      "Squeeze the bicep at the top.",
      "Lower with control while rotating back.",
      "Alternate or do both at once.",
    ],
    tips: ["Slight rotation maximizes bicep contraction.", "Keep elbows still."],
  },
  {
    id: "55", name: "Hammer Curl", focus: "reps_weight", equipment: "Dumbbell", category: "Arms",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Biceps", "Brachialis"], secondaryMuscles: ["Forearms"],
    description: "Builds bicep thickness and forearm size with neutral grip.",
    instructions: [
      "Stand with dumbbells at your sides, palms facing each other.",
      "Curl the dumbbells up while keeping palms facing in.",
      "Squeeze at the top.",
      "Lower with control.",
    ],
    tips: ["Targets brachialis — adds bicep thickness.", "Keep wrists neutral throughout."],
  },
  {
    id: "56", name: "Preacher Curl", focus: "reps_weight", equipment: "Barbell", category: "Arms",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Biceps"], secondaryMuscles: ["Forearms"],
    description: "Locks elbows in place, eliminating cheating and isolating biceps.",
    instructions: [
      "Sit at the preacher bench with armpits pressed against the top of the pad.",
      "Grip the bar shoulder-width with palms up.",
      "Curl the bar up toward your shoulders.",
      "Squeeze at the top.",
      "Lower slowly to a full stretch.",
    ],
    tips: ["Don't fully lock out the elbows at the bottom.", "Light to moderate weight only — full ROM is risky heavy."],
  },
  {
    id: "57", name: "Concentration Curl", focus: "reps_weight", equipment: "Dumbbell", category: "Arms",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Biceps"], secondaryMuscles: ["Forearms"],
    description: "Maximum bicep isolation with the elbow braced against the inner thigh.",
    instructions: [
      "Sit on a bench with legs spread, holding a dumbbell in one hand.",
      "Brace the working elbow against the inside of your thigh.",
      "Curl the dumbbell up toward your shoulder.",
      "Squeeze hard at the top.",
      "Lower slowly to full extension.",
    ],
    tips: ["Slow tempo, max squeeze.", "Use moderate weight — form first."],
  },
  {
    id: "58", name: "Cable Curl", focus: "reps_weight", equipment: "Cable", category: "Arms",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Biceps"], secondaryMuscles: ["Forearms"],
    description: "Constant tension throughout the movement.",
    instructions: [
      "Stand at a low pulley with a straight or EZ bar attached.",
      "Grip the bar shoulder-width, palms up.",
      "Curl the bar up to shoulders.",
      "Squeeze at the top.",
      "Lower with control to full extension.",
    ],
    tips: ["Cable keeps tension at the top, unlike free weights.", "Stand close to the pulley."],
  },
  {
    id: "59", name: "Tricep Pushdown", focus: "reps_weight", equipment: "Cable", category: "Arms",
    movementPattern: "isolation_extension",
    primaryMuscles: ["Triceps"], secondaryMuscles: [],
    description: "Tricep isolation staple for thick horseshoe arms.",
    instructions: [
      "Stand at a high pulley with rope or straight bar attached.",
      "Grip with elbows pinned to your sides, forearms parallel to floor.",
      "Push the attachment down by extending elbows.",
      "Fully extend at the bottom.",
      "Slowly return to start, keeping elbows pinned.",
    ],
    tips: ["Elbows don't move — only forearms.", "Squeeze triceps hard at the bottom."],
  },
  {
    id: "60", name: "Skull Crusher", focus: "reps_weight", equipment: "Barbell", category: "Arms",
    movementPattern: "isolation_extension",
    primaryMuscles: ["Triceps"], secondaryMuscles: [],
    description: "Lying tricep extension that crushes the long head.",
    instructions: [
      "Lie on a bench with an EZ bar held over your chest, arms straight.",
      "Keeping upper arms vertical, bend at the elbows.",
      "Lower the bar toward your forehead (or just past).",
      "Extend the elbows back to start.",
    ],
    tips: ["Elbows stay pointed up — don't flare them out.", "Move slowly to protect elbow joints."],
  },
  {
    id: "61", name: "Overhead Tricep Extension", focus: "reps_weight", equipment: "Dumbbell", category: "Arms",
    movementPattern: "isolation_extension",
    primaryMuscles: ["Triceps"], secondaryMuscles: [],
    description: "Stretched-position tricep work for max long-head growth.",
    instructions: [
      "Hold a dumbbell vertically with both hands cupping the top.",
      "Press it overhead so arms are extended.",
      "Bend elbows to lower the dumbbell behind your head.",
      "Get a full stretch.",
      "Extend back overhead by squeezing triceps.",
    ],
    tips: ["Keep elbows close to head, pointing up.", "Use moderate weight only."],
  },
  {
    id: "62", name: "Tricep Dip", focus: "reps_weight", equipment: "Bodyweight", category: "Arms",
    movementPattern: "vertical_push",
    primaryMuscles: ["Triceps"], secondaryMuscles: ["Pectoralis", "Front Deltoids"],
    description: "Compound bodyweight movement that hammers the triceps.",
    instructions: [
      "Grip parallel bars and press up to a supported start.",
      "Keep torso upright (don't lean forward).",
      "Lower yourself by bending elbows straight back.",
      "Stop when upper arms are parallel to the floor.",
      "Press back up to lockout.",
    ],
    tips: ["Upright = more triceps.", "Add weight with a dip belt to progress."],
  },
  {
    id: "63", name: "Close-Grip Bench Press", focus: "reps_weight", equipment: "Barbell", category: "Arms",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Triceps"], secondaryMuscles: ["Pectoralis", "Front Deltoids"],
    description: "Heavy compound tricep builder.",
    instructions: [
      "Lie on a bench with hands shoulder-width or slightly closer on the bar.",
      "Unrack and hold over your chest.",
      "Lower the bar to lower chest with elbows tucked tight.",
      "Press back up explosively.",
    ],
    tips: ["Don't grip too narrow — wrists hate it.", "Elbows track close to the body."],
  },
  {
    id: "64", name: "Cable Hammer Curl", focus: "reps_weight", equipment: "Cable", category: "Arms",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Biceps", "Brachialis"], secondaryMuscles: ["Forearms"],
    description: "Cable version with constant tension on biceps and forearms.",
    instructions: [
      "Attach a rope to a low pulley.",
      "Grip the rope with palms facing each other (neutral).",
      "Curl the rope up toward your shoulders.",
      "Squeeze at the top.",
      "Lower with control.",
    ],
    tips: ["Keep elbows pinned at sides.", "Maintain neutral grip throughout."],
  },
  {
    id: "65", name: "Wrist Curl", focus: "reps_weight", equipment: "Dumbbell", category: "Arms",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Forearms"], secondaryMuscles: [],
    description: "Direct forearm flexor work for a powerful grip.",
    instructions: [
      "Sit on a bench with forearms resting on your thighs, hands hanging off.",
      "Hold a dumbbell with palm facing up.",
      "Let the dumbbell roll down to your fingertips.",
      "Curl the dumbbell up by flexing your wrist.",
      "Lower with control.",
    ],
    tips: ["High reps work well here.", "Keep forearms anchored on legs."],
  },

  // ============ CORE ============
  {
    id: "66", name: "Plank", focus: "time", equipment: "Bodyweight", category: "Core",
    movementPattern: "static",
    primaryMuscles: ["Core", "Abs"], secondaryMuscles: ["Shoulders", "Glutes"],
    description: "Foundational isometric core hold for stability and endurance.",
    instructions: [
      "Set up on forearms with elbows under shoulders.",
      "Extend legs back, balancing on toes.",
      "Keep body in a straight line head to heels.",
      "Brace abs and glutes hard.",
      "Hold for the prescribed time.",
    ],
    tips: ["Don't let hips sag or pike.", "Quality over quantity — perfect form 30s beats sloppy 2min."],
  },
  {
    id: "67", name: "Hanging Leg Raise", focus: "reps_weight", equipment: "Bodyweight", category: "Core",
    movementPattern: "core",
    primaryMuscles: ["Lower Abs", "Hip Flexors"], secondaryMuscles: ["Obliques"],
    description: "Tough but elite ab exercise that hits the lower abs.",
    instructions: [
      "Hang from a pull-up bar with arms straight.",
      "Keep legs straight (or bent if too hard).",
      "Raise legs up until they're parallel to the floor (or higher).",
      "Lower with control to a full hang.",
    ],
    tips: ["Don't swing — strict form only.", "Bend knees if you can't do straight legs."],
  },
  {
    id: "68", name: "Cable Crunch", focus: "reps_weight", equipment: "Cable", category: "Core",
    movementPattern: "core",
    primaryMuscles: ["Abs"], secondaryMuscles: [],
    description: "Loaded ab work for thick, blocky abs.",
    instructions: [
      "Kneel facing a high pulley with a rope attachment.",
      "Hold the rope on either side of your head.",
      "Crunch down by curling your spine, bringing elbows toward thighs.",
      "Squeeze abs hard at the bottom.",
      "Slowly return to upright.",
    ],
    tips: ["Move from the abs, not the hips.", "Keep hips locked in place."],
  },
  {
    id: "69", name: "Russian Twist", focus: "reps_weight", equipment: "Bodyweight", category: "Core",
    movementPattern: "core",
    primaryMuscles: ["Obliques", "Abs"], secondaryMuscles: [],
    description: "Rotational ab exercise that builds the obliques.",
    instructions: [
      "Sit on the floor with knees bent and feet lifted (or down for easier).",
      "Lean back slightly to engage the core.",
      "Hold a weight or just clasp hands together.",
      "Rotate the weight from side to side, touching the floor each rep.",
    ],
    tips: ["Move from the core, not just the arms.", "Keep chest up to protect the lower back."],
  },
  {
    id: "70", name: "Ab Wheel Rollout", focus: "reps_weight", equipment: "Bodyweight", category: "Core",
    movementPattern: "core",
    primaryMuscles: ["Abs", "Core"], secondaryMuscles: ["Lats", "Shoulders"],
    description: "One of the toughest ab exercises — builds elite core strength.",
    instructions: [
      "Kneel and grip an ab wheel in front of you.",
      "Brace abs hard.",
      "Roll the wheel forward, extending your body.",
      "Stop just before your hips would sag.",
      "Pull yourself back to start using your abs.",
    ],
    tips: ["Don't let lower back arch.", "Start with short rollouts and progress slowly."],
  },
  {
    id: "71", name: "Bicycle Crunch", focus: "reps_weight", equipment: "Bodyweight", category: "Core",
    movementPattern: "core",
    primaryMuscles: ["Abs", "Obliques"], secondaryMuscles: [],
    description: "Dynamic ab exercise that hits the rectus and obliques together.",
    instructions: [
      "Lie on your back with hands behind your head.",
      "Lift shoulder blades and legs off the floor.",
      "Bring one knee in while rotating the opposite elbow toward it.",
      "Switch sides in a pedaling motion.",
    ],
    tips: ["Slow controlled reps beat fast sloppy ones.", "Don't pull on your neck."],
  },
  {
    id: "72", name: "Side Plank", focus: "time", equipment: "Bodyweight", category: "Core",
    movementPattern: "static",
    primaryMuscles: ["Obliques", "Core"], secondaryMuscles: ["Shoulders", "Glutes"],
    description: "Builds lateral core stability and strong obliques.",
    instructions: [
      "Lie on your side with elbow under shoulder, legs stacked.",
      "Lift your hips so your body forms a straight line.",
      "Hold the position, keeping hips high.",
      "Repeat on other side.",
    ],
    tips: ["Don't let hips drop.", "Free hand can be on hip or extended up."],
  },
  {
    id: "73", name: "Dead Bug", focus: "reps_weight", equipment: "Bodyweight", category: "Core",
    movementPattern: "core",
    primaryMuscles: ["Abs", "Core"], secondaryMuscles: ["Hip Flexors"],
    description: "Beginner-friendly anti-extension core exercise.",
    instructions: [
      "Lie on back with arms extended up and knees bent over hips at 90°.",
      "Slowly lower opposite arm and leg toward the floor.",
      "Stop just before they touch.",
      "Return to start and switch sides.",
    ],
    tips: ["Press lower back into the floor.", "Move slowly with control."],
  },
  {
    id: "74", name: "Mountain Climber", focus: "time", equipment: "Bodyweight", category: "Core",
    movementPattern: "core",
    primaryMuscles: ["Core", "Hip Flexors"], secondaryMuscles: ["Shoulders", "Quads"],
    description: "Cardio-core hybrid that burns and builds.",
    instructions: [
      "Start in a high plank position.",
      "Drive one knee toward your chest.",
      "Quickly switch legs, alternating in a running motion.",
      "Maintain plank position throughout.",
    ],
    tips: ["Keep hips low and stable.", "Speed = cardio, slow = core focus."],
  },

  // ============ CARDIO ============
  {
    id: "75", name: "Treadmill Run", focus: "distance", equipment: "Machine", category: "Cardio",
    movementPattern: "cardio",
    primaryMuscles: ["Quadriceps", "Calves"], secondaryMuscles: ["Glutes", "Hamstrings", "Core"],
    description: "Steady-state running for cardiovascular endurance.",
    instructions: [
      "Step on the treadmill and start at a slow walking pace.",
      "Gradually increase to your target running speed.",
      "Maintain a tall posture and short, quick strides.",
      "Cool down with a walk for 3-5 minutes.",
    ],
    tips: ["Don't hold the rails — defeats the purpose.", "Set incline 1-2% to mimic outdoor running."],
  },
  {
    id: "76", name: "Cycling", focus: "time", equipment: "Machine", category: "Cardio",
    movementPattern: "cardio",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Hamstrings", "Calves"],
    description: "Low-impact cardio with great quad development.",
    instructions: [
      "Adjust seat so knee is slightly bent at the bottom of the stroke.",
      "Set resistance to a challenging but maintainable level.",
      "Pedal at 70-90 RPM.",
      "Vary intensity for intervals or maintain steady state.",
    ],
    tips: ["Don't lock knees at the bottom.", "Engage glutes — don't just push with quads."],
  },
  {
    id: "77", name: "Rowing Machine", focus: "distance", equipment: "Machine", category: "Cardio",
    movementPattern: "cardio",
    primaryMuscles: ["Lats", "Quadriceps", "Glutes"], secondaryMuscles: ["Biceps", "Core", "Hamstrings"],
    description: "Full-body cardio that builds strength and endurance simultaneously.",
    instructions: [
      "Strap feet in and grip the handle.",
      "Drive: push with legs, then pull with arms, leaning back slightly.",
      "Recover: arms forward, lean over, then bend knees back to start.",
      "Maintain rhythm — legs, body, arms, then arms, body, legs.",
    ],
    tips: ["80% leg drive, 20% arms.", "Don't rush the recovery."],
  },
  {
    id: "78", name: "Stair Climber", focus: "time", equipment: "Machine", category: "Cardio",
    movementPattern: "cardio",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Calves", "Hamstrings"],
    description: "Killer leg-and-cardio combo that targets the glutes.",
    instructions: [
      "Step onto the stair climber and grip the rails for balance only.",
      "Step at a steady pace with full leg extension.",
      "Don't lean on the rails — stand tall.",
    ],
    tips: ["Drive through the heels.", "Slightly lean forward to engage glutes more."],
  },
  {
    id: "79", name: "Jump Rope", focus: "time", equipment: "Bodyweight", category: "Cardio",
    movementPattern: "cardio",
    primaryMuscles: ["Calves"], secondaryMuscles: ["Shoulders", "Forearms", "Core"],
    description: "Highly efficient cardio that improves footwork and coordination.",
    instructions: [
      "Hold rope handles at your sides.",
      "Swing the rope from the wrists, not the arms.",
      "Jump just enough to clear the rope (1-2 inches).",
      "Land softly on the balls of your feet.",
    ],
    tips: ["Wrist-driven — not arm-driven.", "Build up time gradually to avoid calf soreness."],
  },
  {
    id: "80", name: "Burpee", focus: "reps_weight", equipment: "Bodyweight", category: "Cardio",
    movementPattern: "cardio",
    primaryMuscles: ["Full Body"], secondaryMuscles: [],
    description: "The ultimate full-body conditioning exercise — and the one everyone hates.",
    instructions: [
      "Stand tall, then squat down and place hands on the floor.",
      "Kick feet back into a high plank.",
      "Optional: do a push-up.",
      "Jump feet back to your hands.",
      "Explode up with a jump and clap overhead.",
    ],
    tips: ["Pace yourself — they're brutal.", "Skip the push-up if too tough."],
  },

  // ============ MORE CHEST/BACK/LEGS variations ============
  {
    id: "81", name: "Landmine Press", focus: "reps_weight", equipment: "Barbell", category: "Shoulders",
    movementPattern: "vertical_push",
    primaryMuscles: ["Front Deltoids", "Upper Pectoralis"], secondaryMuscles: ["Triceps", "Core"],
    description: "Shoulder-friendly pressing variation using a landmine setup.",
    instructions: [
      "Set up a barbell in a landmine attachment.",
      "Hold the bar end at your shoulder, elbow tucked.",
      "Press the bar up and slightly forward.",
      "Lower with control to your shoulder.",
    ],
    tips: ["Brace core hard.", "Great for those with overhead pressing issues."],
  },
  {
    id: "82", name: "Inverted Row", focus: "reps_weight", equipment: "Bodyweight", category: "Back",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["Lats", "Rhomboids"], secondaryMuscles: ["Biceps", "Rear Deltoids"],
    description: "Bodyweight horizontal pull — great push-up complement.",
    instructions: [
      "Set a barbell in a rack at hip height (or use a TRX).",
      "Lie under the bar and grip with hands shoulder-width.",
      "Hang with arms extended, body straight.",
      "Pull your chest up to the bar.",
      "Lower with control.",
    ],
    tips: ["Lower bar = harder.", "Keep body in a straight line."],
  },
  {
    id: "83", name: "Good Morning", focus: "reps_weight", equipment: "Barbell", category: "Legs",
    movementPattern: "hinge",
    primaryMuscles: ["Hamstrings", "Glutes", "Erector Spinae"], secondaryMuscles: [],
    description: "Hip hinge variation that hammers the posterior chain.",
    instructions: [
      "Set up like a back squat with the bar on your upper back.",
      "Soften knees and brace core.",
      "Hinge at hips, lowering torso toward parallel.",
      "Drive hips forward to return to standing.",
    ],
    tips: ["Keep neutral spine.", "Use lighter weight than squats."],
  },
  {
    id: "84", name: "Reverse Lunge", focus: "reps_weight", equipment: "Dumbbell", category: "Legs",
    movementPattern: "lunge",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Hamstrings"],
    description: "Knee-friendlier lunge variation that emphasizes glutes.",
    instructions: [
      "Stand holding dumbbells at sides.",
      "Step one foot back into a lunge, lowering the back knee toward the floor.",
      "Drive through the front heel to return to standing.",
      "Alternate or do all reps on one side.",
    ],
    tips: ["Easier on the knees than forward lunges.", "Keep front shin vertical."],
  },
  {
    id: "85", name: "Box Jump", focus: "reps_weight", equipment: "Bodyweight", category: "Legs",
    movementPattern: "squat",
    primaryMuscles: ["Quadriceps", "Glutes", "Calves"], secondaryMuscles: ["Hamstrings"],
    description: "Power-building plyometric for explosive legs.",
    instructions: [
      "Stand in front of a sturdy box.",
      "Drop into a quarter squat and swing arms back.",
      "Explosively jump up and land softly on top of the box with bent knees.",
      "Stand up fully.",
      "Step (don't jump) back down.",
    ],
    tips: ["Step down — jumping down stresses joints.", "Start with a low box and progress."],
  },
  {
    id: "86", name: "Single-Leg Romanian Deadlift", focus: "reps_weight", equipment: "Dumbbell", category: "Legs",
    movementPattern: "hinge",
    primaryMuscles: ["Hamstrings", "Glutes"], secondaryMuscles: ["Core", "Erector Spinae"],
    description: "Unilateral hinge that builds balance, hamstrings, and glutes.",
    instructions: [
      "Stand on one leg holding a dumbbell in the opposite hand.",
      "Hinge at the hip, extending the back leg behind you.",
      "Lower until torso is parallel to the floor.",
      "Drive through the standing heel to return.",
    ],
    tips: ["Imagine a wine glass on your back not spilling.", "Use a wall for balance if needed."],
  },
  {
    id: "87", name: "Cable Pull-Through", focus: "reps_weight", equipment: "Cable", category: "Legs",
    movementPattern: "hinge",
    primaryMuscles: ["Glutes", "Hamstrings"], secondaryMuscles: ["Erector Spinae"],
    description: "Glute-focused hip hinge that's easy on the lower back.",
    instructions: [
      "Set cable to lowest setting with rope attachment.",
      "Stand facing away from the machine, rope between legs.",
      "Hinge at the hips, sitting back as the rope pulls between your legs.",
      "Drive hips forward to stand up, squeezing glutes hard at the top.",
    ],
    tips: ["Keep arms straight — don't curl the rope.", "Focus on glute drive, not back extension."],
  },
  {
    id: "88", name: "Dumbbell Pullover", focus: "reps_weight", equipment: "Dumbbell", category: "Back",
    movementPattern: "vertical_pull",
    primaryMuscles: ["Lats", "Pectoralis"], secondaryMuscles: ["Triceps", "Serratus"],
    description: "Old-school exercise that hits chest, lats, and serratus.",
    instructions: [
      "Lie across a bench with only your upper back supported.",
      "Hold a dumbbell vertically with both hands above your chest.",
      "Lower the dumbbell back behind your head with a slight elbow bend.",
      "Get a deep stretch.",
      "Pull the dumbbell back over your chest.",
    ],
    tips: ["Keep slight bend in elbows throughout.", "Don't drop hips — keep them up."],
  },
  {
    id: "89", name: "Spider Curl", focus: "reps_weight", equipment: "Dumbbell", category: "Arms",
    movementPattern: "isolation_curl",
    primaryMuscles: ["Biceps"], secondaryMuscles: [],
    description: "Incline bench bicep curl that fully isolates and stretches the biceps.",
    instructions: [
      "Lie chest-down on an incline bench, dumbbells hanging straight down.",
      "Curl the dumbbells up by squeezing biceps.",
      "Squeeze hard at the top.",
      "Lower slowly to a full stretch.",
    ],
    tips: ["No body english possible — pure bicep work.", "Use moderate weight."],
  },
  {
    id: "90", name: "Diamond Push-up", focus: "reps_weight", equipment: "Bodyweight", category: "Arms",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Triceps"], secondaryMuscles: ["Pectoralis", "Front Deltoids"],
    description: "Close-grip push-up variation for tricep emphasis.",
    instructions: [
      "Set up in push-up position with hands close, forming a diamond shape with thumbs and index fingers.",
      "Lower chest to your hands, keeping elbows tucked tight.",
      "Push back up to start.",
    ],
    tips: ["Hardest if your chest touches your hands.", "Knees down to scale."],
  },
  {
    id: "91", name: "Farmer's Carry", focus: "distance", equipment: "Dumbbell", category: "Core",
    movementPattern: "carry",
    primaryMuscles: ["Forearms", "Traps", "Core"], secondaryMuscles: ["Quads", "Glutes"],
    description: "Loaded carry that builds total-body strength and grip.",
    instructions: [
      "Pick up a heavy dumbbell in each hand.",
      "Stand tall with shoulders back.",
      "Walk for distance with controlled steps.",
      "Maintain posture — don't lean to either side.",
    ],
    tips: ["Heavier than you think.", "Builds incredible grip and core strength."],
  },
  {
    id: "92", name: "Trap Bar Deadlift", focus: "reps_weight", equipment: "Barbell", category: "Legs",
    movementPattern: "hinge",
    primaryMuscles: ["Quadriceps", "Glutes", "Hamstrings"], secondaryMuscles: ["Erector Spinae", "Traps"],
    description: "Friendlier deadlift variation — easier to learn and safer for the back.",
    instructions: [
      "Step inside a trap bar (hex bar) with feet shoulder-width.",
      "Squat down and grip the handles at your sides.",
      "Lift chest, brace core.",
      "Drive through heels to stand up.",
      "Lower the bar with control to the floor.",
    ],
    tips: ["More quad-dominant than conventional deadlift.", "Great for beginners or those with back issues."],
  },
  {
    id: "93", name: "Glute Bridge", focus: "reps_weight", equipment: "Bodyweight", category: "Legs",
    movementPattern: "hinge",
    primaryMuscles: ["Glutes"], secondaryMuscles: ["Hamstrings", "Core"],
    description: "Foundational glute exercise — bodyweight version of the hip thrust.",
    instructions: [
      "Lie on your back, knees bent, feet flat on the floor.",
      "Drive through heels to lift hips toward the ceiling.",
      "Squeeze glutes hard at the top.",
      "Lower with control.",
    ],
    tips: ["Add weight on hips to progress.", "Squeeze for 1-2 seconds at the top."],
  },
  {
    id: "94", name: "Cable Tricep Kickback", focus: "reps_weight", equipment: "Cable", category: "Arms",
    movementPattern: "isolation_extension",
    primaryMuscles: ["Triceps"], secondaryMuscles: [],
    description: "Tricep isolation that emphasizes contraction in the lockout.",
    instructions: [
      "Set cable to low setting and grab single handle.",
      "Hinge forward at the hips, upper arm parallel to floor, elbow bent 90°.",
      "Extend the elbow to straighten the arm behind you.",
      "Squeeze tricep at the top.",
      "Return slowly.",
    ],
    tips: ["Upper arm stays still.", "Light weight — focus on the squeeze."],
  },
  {
    id: "95", name: "Smith Machine Squat", focus: "reps_weight", equipment: "Machine", category: "Legs",
    movementPattern: "squat",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Hamstrings"],
    description: "Stable squat variation good for high volume or learning.",
    instructions: [
      "Position bar across upper traps in the Smith machine.",
      "Set feet slightly forward of the bar.",
      "Unrack and squat down until thighs are parallel.",
      "Drive up through heels.",
    ],
    tips: ["Feet forward = quad-dominant.", "Don't replace barbell squats long-term."],
  },
  {
    id: "96", name: "Cable Fly", focus: "reps_weight", equipment: "Cable", category: "Chest",
    movementPattern: "horizontal_push",
    primaryMuscles: ["Pectoralis Major"], secondaryMuscles: ["Front Deltoids"],
    description: "Constant tension chest fly using cable at any height.",
    instructions: [
      "Set cables at chest height.",
      "Stand between with handles in each hand.",
      "Step forward into a split stance.",
      "Bring handles together in front of chest in a hugging motion.",
      "Squeeze chest, then return slowly.",
    ],
    tips: ["Vary cable height to hit different chest fibers.", "Keep slight elbow bend throughout."],
  },
  {
    id: "97", name: "Reverse Grip Pulldown", focus: "reps_weight", equipment: "Cable", category: "Back",
    movementPattern: "vertical_pull",
    primaryMuscles: ["Lats", "Biceps"], secondaryMuscles: ["Rhomboids"],
    description: "Underhand pulldown that hits lower lats and biceps hard.",
    instructions: [
      "Sit at the lat pulldown with shoulder-width underhand grip.",
      "Pull the bar down to your upper chest.",
      "Squeeze lats and pause.",
      "Slowly let the bar return up.",
    ],
    tips: ["Keep elbows close to your body.", "Drive elbows down and back."],
  },
  {
    id: "98", name: "Zercher Squat", focus: "reps_weight", equipment: "Barbell", category: "Legs",
    movementPattern: "squat",
    primaryMuscles: ["Quadriceps", "Glutes"], secondaryMuscles: ["Core", "Upper Back", "Biceps"],
    description: "Brutal front-loaded squat that demands core and upper back strength.",
    instructions: [
      "Hold a barbell in the crook of your elbows, hands clasped.",
      "Stand with feet shoulder-width.",
      "Squat down keeping torso upright.",
      "Drive up through heels.",
    ],
    tips: ["Use a pad on the bar — it WILL hurt your arms.", "Builds an unbreakable core."],
  },
  {
    id: "99", name: "Pallof Press", focus: "reps_weight", equipment: "Cable", category: "Core",
    movementPattern: "core",
    primaryMuscles: ["Obliques", "Core"], secondaryMuscles: ["Shoulders"],
    description: "Anti-rotation core exercise that builds true core stability.",
    instructions: [
      "Stand sideways to a cable at chest height with handle at chest.",
      "Step away from the machine to create tension.",
      "Press the handle straight out from your chest.",
      "Resist the cable's pull to rotate you.",
      "Return to chest, repeat for reps, then switch sides.",
    ],
    tips: ["Slow and controlled.", "Brace core like you're about to take a punch."],
  },
  {
    id: "100", name: "Battle Ropes", focus: "time", equipment: "Bodyweight", category: "Cardio",
    movementPattern: "cardio",
    primaryMuscles: ["Shoulders", "Core"], secondaryMuscles: ["Arms", "Back"],
    description: "Conditioning tool that taxes the upper body and cardio system.",
    instructions: [
      "Anchor heavy ropes and grip an end in each hand.",
      "Stand in athletic stance, knees bent.",
      "Slam ropes up and down alternately or simultaneously.",
      "Maintain intensity for the prescribed time.",
    ],
    tips: ["Move from the hips and core, not just arms.", "30-second intervals work great."],
  },
];
